"""AI Trade Skill Extractor — Pipeline Orchestrator

Usage:
  python main.py --playlist URL [options]

Options:
  --playlist URL    YouTube playlist URL (required)
  --resume          Resume from last checkpoint
  --stage N         Run only stage N (1-5)
  --dry-run         Show plan without executing

Stages:
  1 - Data Collection     (playlist → video manifest)
  2 - Transcript Extract  (videos → text files)
  3 - Logic Extraction    (text → trading logic JSON via Claude)
  4 - Skill Organization  (logic → knowledge_base/ categories)
  5 - MQL5 Templates      (skills → .mq5 pseudocode files)
"""

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import ANTHROPIC_API_KEY, CATALOG_FILE, REPORTS_DIR, ROOT_DIR


def parse_args():
    parser = argparse.ArgumentParser(
        description="AI Trade Skill Extractor — YouTube → MT5 Knowledge Base",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--playlist", help="YouTube playlist URL")
    parser.add_argument("--resume", action="store_true", help="Resume from checkpoint")
    parser.add_argument("--stage", type=int, choices=[1, 2, 3, 4, 5], help="Run single stage only")
    parser.add_argument("--dry-run", action="store_true", help="Show plan, do not execute")
    return parser.parse_args()


def check_requirements():
    errors = []
    try:
        import yt_dlp  # noqa
    except ImportError:
        errors.append("yt-dlp not installed: pip install yt-dlp")

    try:
        import youtube_transcript_api  # noqa
    except ImportError:
        errors.append("youtube-transcript-api not installed: pip install youtube-transcript-api")

    try:
        import anthropic  # noqa
    except ImportError:
        errors.append("anthropic not installed: pip install anthropic")

    try:
        import slugify  # noqa
    except ImportError:
        errors.append("python-slugify not installed: pip install python-slugify")

    if errors:
        print("Missing dependencies:")
        for e in errors:
            print(f"  - {e}")
        print("\nInstall all: pip install -r requirements.txt")
        sys.exit(1)


def print_banner():
    print("""
╔═══════════════════════════════════════════════════╗
║     AI TRADE SKILL EXTRACTOR  v2.0                ║
║     YouTube Playlist → MT5 Knowledge Base          ║
╚═══════════════════════════════════════════════════╝
""")


def write_report(start_time: float, stats: dict):
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    elapsed = time.time() - start_time
    minutes = int(elapsed // 60)
    seconds = int(elapsed % 60)

    skills_total = 0
    if CATALOG_FILE.exists():
        with open(CATALOG_FILE) as f:
            catalog = json.load(f)
        skills_total = len(catalog)

    lines = [
        "# AI Trade Skill Extractor — Pipeline Report",
        f"\n**Run Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Duration:** {minutes}m {seconds}s",
        "",
        "## Results",
        f"| Stage | Result |",
        f"|-------|--------|",
        f"| 1. Data Collection | {stats.get('videos_collected', 0)} videos |",
        f"| 2. Transcripts | {stats.get('transcripts_done', 0)} extracted, {stats.get('transcripts_skip', 0)} skipped |",
        f"| 3. Logic Extraction | {stats.get('logic_done', 0)} processed, {stats.get('logic_errors', 0)} errors |",
        f"| 4. Skill Organization | {stats.get('skills_created', 0)} created, {stats.get('skills_merged', 0)} merged |",
        f"| 5. MQL5 Templates | {stats.get('templates', 0)} generated |",
        "",
        f"**Total Skills in Knowledge Base:** {skills_total}",
        "",
        "## Knowledge Base Location",
        f"`{ROOT_DIR}/knowledge_base/skills/`",
        "",
        "## Next Steps",
        "1. Review skills in `knowledge_base/skills/` folders",
        "2. Use `mt5-coder` agent to complete `.mq5` template stubs",
        "3. Run backtests with `mt5-backtester` agent",
        "4. High-risk strategies (grid/martingale) require manual review before use",
        "",
        "---",
        "*Auto-generated by AI Trade Skill Extractor*",
    ]

    report_path = REPORTS_DIR / "pipeline_summary.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nReport saved: {report_path}")


def main():
    print_banner()
    args = parse_args()
    check_requirements()

    if not args.playlist and not args.stage:
        print("ERROR: --playlist URL is required\n")
        print(__doc__)
        sys.exit(1)

    if args.stage and args.stage == 3 and not ANTHROPIC_API_KEY:
        print("ERROR: ANTHROPIC_API_KEY not set in .env file")
        sys.exit(1)

    if args.dry_run:
        print("[DRY RUN] Would execute stages:")
        stages = [args.stage] if args.stage else [1, 2, 3, 4, 5]
        for s in stages:
            print(f"  Stage {s}")
        print(f"  Playlist: {args.playlist or '(current checkpoint)'}")
        return

    from data_collector import collect_playlist
    from transcript_extractor import extract_transcripts
    from logic_extractor import extract_logic
    from skill_organizer import organize_skills
    from backtest_engine import generate_templates

    start_time = time.time()
    stats = {}
    run_stages = [args.stage] if args.stage else [1, 2, 3, 4, 5]

    if 1 in run_stages:
        manifest = collect_playlist(args.playlist, resume=args.resume)
        stats["videos_collected"] = manifest.get("total_videos", 0)

    if 2 in run_stages:
        result = extract_transcripts(resume=args.resume)
        stats["transcripts_done"] = len(result.get("done", []))
        stats["transcripts_skip"] = len(result.get("skip", []))

    if 3 in run_stages:
        if not ANTHROPIC_API_KEY:
            print("\n[Stage 3] SKIPPED — ANTHROPIC_API_KEY not set")
            print("  Set it in .env file and re-run with --stage 3 --resume")
        else:
            result = extract_logic(resume=args.resume)
            stats["logic_done"] = len(result.get("done", []))
            stats["logic_errors"] = len(result.get("errors", []))

    if 4 in run_stages:
        result = organize_skills()
        stats["skills_created"] = result.get("skills_created", 0)
        stats["skills_merged"] = result.get("skills_merged", 0)

    if 5 in run_stages:
        count = generate_templates()
        stats["templates"] = count

    write_report(start_time, stats)

    elapsed = time.time() - start_time
    print(f"\n✓ Pipeline complete in {int(elapsed // 60)}m {int(elapsed % 60)}s")


if __name__ == "__main__":
    main()
