"""Stage 4: Organize extracted logic into categorized skill library."""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from slugify import slugify

from config import (
    EXTRACTED_DIR,
    KNOWLEDGE_BASE_DIR,
    CATALOG_FILE,
    SKILL_CATEGORIES,
    CATEGORY_DISPLAY,
)

SKILL_MD_TEMPLATE = """# {name}

**Category:** {category_display}
**Skill ID:** `{skill_id}`
**Confidence:** {confidence_score:.0%}
**Source Videos:** {source_count}

## Indicators
{indicators}

## Timeframes & Symbols
- **Timeframes:** {timeframes}
- **Symbols:** {symbols}

## Entry Conditions

### Long (Buy)
{long_conditions}

### Short (Sell)
{short_conditions}

## Exit Rules
- **Take Profit:** {tp_method}
- **Stop Loss:** {sl_method}
- **Trailing Stop:** {trailing_stop}

## Risk Rules
- **Max Risk Per Trade:** {max_risk_pct}%
- **Risk:Reward Ratio:** 1:{rr_ratio}
- **Filters:** {filters}

## Notes
{raw_notes}

---
*Auto-generated by AI Trade Skill Extractor — verify before live trading*
"""


def _classify(logic: dict) -> str:
    """Return category key based on indicators and content."""
    text = " ".join([
        " ".join(logic.get("indicators", [])),
        logic.get("raw_notes", ""),
        logic.get("source_title", ""),
    ]).lower()

    for category, keywords in SKILL_CATEGORIES.items():
        if not keywords:
            continue
        if any(kw in text for kw in keywords):
            return category

    return "indicator-combo"


def _make_skill_id(category: str, title: str, video_id: str) -> str:
    slug = slugify(title, max_length=50, separator="-")
    if not slug or all(c == "-" for c in slug):
        slug = video_id[:12]
    return f"{category}-{slug}"


def _ensure_unique_id(skill_id: str, existing_ids: set) -> str:
    if skill_id not in existing_ids:
        return skill_id
    counter = 2
    while f"{skill_id}-v{counter}" in existing_ids:
        counter += 1
    return f"{skill_id}-v{counter}"


def _format_list(items: list, bullet: str = "-") -> str:
    if not items:
        return f"{bullet} (none stated)"
    return "\n".join(f"{bullet} {item}" for item in items)


def _build_skill_md(skill: dict) -> str:
    exit_cond = skill.get("exit_conditions", {})
    risk = skill.get("risk_rules", {})
    entry = skill.get("entry_conditions", {})
    return SKILL_MD_TEMPLATE.format(
        name=skill["name"],
        category_display=CATEGORY_DISPLAY.get(skill["category"], skill["category"]),
        skill_id=skill["skill_id"],
        confidence_score=skill["confidence_score"],
        source_count=len(skill.get("source_videos", [])),
        indicators=_format_list(skill.get("indicators", [])),
        timeframes=", ".join(skill.get("timeframes", [])) or "not specified",
        symbols=", ".join(skill.get("symbols", [])) or "not specified",
        long_conditions=_format_list(entry.get("long", [])),
        short_conditions=_format_list(entry.get("short", [])),
        tp_method=exit_cond.get("tp_method", "not specified"),
        sl_method=exit_cond.get("sl_method", "not specified"),
        trailing_stop=exit_cond.get("trailing_stop") or "none",
        max_risk_pct=risk.get("max_risk_pct", 1.0),
        rr_ratio=risk.get("rr_ratio", 2.0),
        filters=_format_list(risk.get("filters", [])),
        raw_notes=skill.get("raw_notes", "—"),
    )


def organize_skills() -> dict:
    """Load all extracted logic files and organize into knowledge_base."""
    KNOWLEDGE_BASE_DIR.mkdir(parents=True, exist_ok=True)

    logic_files = list(EXTRACTED_DIR.glob("*_logic.json"))
    if not logic_files:
        print("[Stage 4] No extracted logic files found")
        return {"skills_created": 0, "skills_merged": 0}

    catalog = {}
    if CATALOG_FILE.exists():
        with open(CATALOG_FILE) as f:
            catalog = json.load(f)

    existing_ids = set(catalog.keys())
    skills_created = 0
    skills_merged = 0

    print(f"[Stage 4] Skill Organization — {len(logic_files)} logic files")

    for logic_file in logic_files:
        with open(logic_file, encoding="utf-8") as f:
            logic = json.load(f)

        video_id = logic.get("video_id", logic_file.stem.replace("_logic", ""))
        title = logic.get("source_title", "Unknown Strategy")
        category = _classify(logic)
        confidence = float(logic.get("confidence_score", 0))

        high_risk = category == "grid-martingale"

        skill_id = _make_skill_id(category, title, video_id)

        if skill_id in catalog:
            existing = catalog[skill_id]
            if video_id not in existing.get("source_videos", []):
                existing["source_videos"].append(video_id)
                if confidence > existing["confidence_score"]:
                    existing.update({
                        "confidence_score": confidence,
                        "indicators": logic.get("indicators", []),
                        "entry_conditions": logic.get("entry_conditions", {}),
                        "exit_conditions": logic.get("exit_conditions", {}),
                        "risk_rules": logic.get("risk_rules", {}),
                        "raw_notes": logic.get("raw_notes", ""),
                    })
                existing["updated_at"] = datetime.now(timezone.utc).isoformat()
                skills_merged += 1
                print(f"  MERGE  [{category}] {title[:50]}")
        else:
            skill_id = _ensure_unique_id(skill_id, existing_ids)
            existing_ids.add(skill_id)

            skill = {
                "skill_id": skill_id,
                "name": title,
                "category": category,
                "version": 1,
                "confidence_score": confidence,
                "source_videos": [video_id],
                "indicators": logic.get("indicators", []),
                "timeframes": logic.get("timeframes", []),
                "symbols": logic.get("symbols", []),
                "entry_conditions": logic.get("entry_conditions", {}),
                "exit_conditions": logic.get("exit_conditions", {}),
                "risk_rules": logic.get("risk_rules", {}),
                "raw_notes": logic.get("raw_notes", ""),
                "has_valid_sltp": bool(
                    logic.get("exit_conditions", {}).get("sl_method") and
                    logic.get("exit_conditions", {}).get("tp_method")
                ),
                "high_risk": high_risk,
                "created_at": datetime.now(timezone.utc).isoformat(),
                "updated_at": datetime.now(timezone.utc).isoformat(),
            }
            catalog[skill_id] = skill
            skills_created += 1
            print(f"  CREATE [{category}] {title[:50]}")

        skill_dir = KNOWLEDGE_BASE_DIR / category / catalog[skill_id]["skill_id"]
        skill_dir.mkdir(parents=True, exist_ok=True)

        with open(skill_dir / "skill.json", "w", encoding="utf-8") as f:
            json.dump(catalog[skill_id], f, ensure_ascii=False, indent=2)

        with open(skill_dir / "skill.md", "w", encoding="utf-8") as f:
            f.write(_build_skill_md(catalog[skill_id]))

    with open(CATALOG_FILE, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)

    print(f"\n[Stage 4] Done — {skills_created} created, {skills_merged} merged, catalog: {CATALOG_FILE}")
    return {"skills_created": skills_created, "skills_merged": skills_merged}
